const forma = document.getElementById('votos');
forma.addEventListener('submit',(e)=>{

    localStorage.setItem("rodada4","rodada4");
    document.getElementById("btn").disabled = true;
    document.getElementById("10").disabled = true;
    document.getElementById("9").disabled = true;
    document.getElementById("8").disabled = true;
    document.getElementById("7").disabled = true;
    document.getElementById("6").disabled = true;
    document.getElementById("5").disabled = true;
    document.getElementById("4").disabled = true;
    document.getElementById("3").disabled = true;
    document.getElementById("2").disabled = true;
    document.getElementById("1").disabled = true;
    document.getElementById("20").disabled = true;
    document.getElementById("19").disabled = true;
    document.getElementById("18").disabled = true;
    document.getElementById("17").disabled = true;
    document.getElementById("16").disabled = true;
    document.getElementById("15").disabled = true;
    document.getElementById("14").disabled = true;
    document.getElementById("13").disabled = true;
    document.getElementById("12").disabled = true;
    document.getElementById("11").disabled = true;
    document.getElementById("30").disabled = true;
    document.getElementById("29").disabled = true;
    document.getElementById("28").disabled = true;
    document.getElementById("27").disabled = true;
    document.getElementById("26").disabled = true;
    document.getElementById("25").disabled = true;
    document.getElementById("24").disabled = true;
    document.getElementById("23").disabled = true;
    document.getElementById("22").disabled = true;
    document.getElementById("21").disabled = true;
    document.getElementById("10a").disabled = true;
    document.getElementById("9a").disabled = true;
    document.getElementById("8a").disabled = true;
    document.getElementById("7a").disabled = true;
    document.getElementById("6a").disabled = true;
    document.getElementById("5a").disabled = true;
    document.getElementById("4a").disabled = true;
    document.getElementById("3a").disabled = true;
    document.getElementById("2a").disabled = true;
    document.getElementById("1a").disabled = true;
    document.getElementById("20a").disabled = true;
    document.getElementById("19a").disabled = true;
    document.getElementById("18a").disabled = true;
    document.getElementById("17a").disabled = true;
    document.getElementById("16a").disabled = true;
    document.getElementById("15a").disabled = true;
    document.getElementById("14a").disabled = true;
    document.getElementById("13a").disabled = true;
    document.getElementById("12a").disabled = true;
    document.getElementById("11a").disabled = true;
    document.getElementById("30a").disabled = true;
    document.getElementById("29a").disabled = true;
    document.getElementById("28a").disabled = true;
    document.getElementById("27a").disabled = true;
    document.getElementById("26a").disabled = true;
    document.getElementById("25a").disabled = true;
    document.getElementById("24a").disabled = true;
    document.getElementById("23a").disabled = true;
    document.getElementById("22a").disabled = true;
    document.getElementById("21a").disabled = true;
    location.reload();

        }
    );

